export const books = [
  {
    id: 1,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51DF6ZR8G7L._SX329_BO1,204,203,200_.jpg",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    rating: "9.6/10",
    genre: "HP",
  },
  {
    id: 2,
    image: "https://images-na.ssl-images-amazon.com/images/I/91HHqVTAJQL.jpg",
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    rating: "9.2/10",
    genre: "HP",
  },
  {
    id: 3,
    image: "https://images-na.ssl-images-amazon.com/images/I/81EbEWM54ML.jpg",
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    rating: "9.7/10",
    genre: "HP",
  },
  {
    id: 4,
    image: "https://images-na.ssl-images-amazon.com/images/I/81t2CVWEsUL.jpg",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    rating: "9.6/10",
    genre: "HP",
  },
  {
    id: 5,
    image: "https://images-na.ssl-images-amazon.com/images/I/91t5-Juqt9L.jpg",
    title: "Harry Potter and the Order of the Pheonix",
    author: "J.K. Rowling",
    rating: "9.8/10",
    genre: "HP",
  },
  {
    id: 6,
    image: "https://images-na.ssl-images-amazon.com/images/I/915i0eI3J8L.jpg",
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    rating: "9.9/10",
    genre: "HP",
  },
  {
    id: 7,
    image: "https://images-na.ssl-images-amazon.com/images/I/71sH3vxziLL.jpg",
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    rating: "9.9/10",
    genre: "HP",
  },
  {
    id: 8,
    image:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546071216l/5907.jpg",
    title: "The Hobbit",
    author: "J.R.R Tolkien",
    rating: "9/10",
    genre: "LOR",
  },
  {
    id: 9,
    image: "https://images-na.ssl-images-amazon.com/images/I/71+8hoMr+0L.jpg",
    title: "The Lord of the Rings - The Fellowship of the Ring",
    author: "J.R.R Tolkien",
    rating: "9.5/10",
    genre: "LOR",
  },
  {
    id: 10,
    image: "https://images-na.ssl-images-amazon.com/images/I/A1y0jd28riL.jpg",
    title: "The Lord of the Rings - The Two Towers",
    author: "J.R.R Tolkien",
    rating: "9.7/10",
    genre: "LOR",
  },
  {
    id: 11,
    image: "https://images-na.ssl-images-amazon.com/images/I/61YLlCTnWtL.jpg",
    title: "The Lord of the Rings - The Return of the King",
    author: "J.R.R Tolkien",
    rating: "9.8/10",
    genre: "LOR",
  },
  {
    id: 12,
    image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630661894l/249747.jpg",
    title: "Artemis Fowl",
    author: "Eoin Colfer",
    rating: "9/10",
    genre: "AF",
  },
  {
    id: 13,
    image: "https://images-na.ssl-images-amazon.com/images/I/81NvdzJuMrL.jpg",
    title: "Artemis Fowl and the Arctic Incident",
    author: "Eoin Colfer",
    rating: "9.2/10",
    genre: "AF",
  },
  {
    id: 14,
    image: "https://images-na.ssl-images-amazon.com/images/I/813rxYImvHL.jpg",
    title: "Artemis Fowl and the Eternity Code",
    author: "Eoin Colfer",
    rating: "9.2/10",
    genre: "AF",
  },
  {
    id: 15,
    image: "https://images-eu.ssl-images-amazon.com/images/I/51ezpwGGQ%2BL._SX342_SY445_QL70_ML2_.jpg",
    title: "Artemis Fowl and the Opal Deception",
    author: "Eoin Colfer",
    rating: "9.1/10",
    genre: "AF",
  },
  {
    id: 16,
    image: "https://images-na.ssl-images-amazon.com/images/I/81fBKkytajL.jpg",
    title: "Artemis Fowl and the Lost Colony",
    author: "Eoin Colfer",
    rating: "9.3/10",
    genre: "AF",
  },
  {
    id: 17,
    image: "https://images-na.ssl-images-amazon.com/images/I/81hTXnCAAlL.jpg",
    title: "Artemis Fowl and the Time Paradox",
    author: "Eoin Colfer",
    rating: "9.4/10",
    genre: "AF",
  },
  {
    id: 18,
    image: "https://img1.od-cdn.com/ImageType-400/0290-1/4B3/4E4/88/%7B4B34E488-FF54-4F86-81AB-1E9AB953E184%7DImg400.jpg",
    title: "Artemis Fowl and the Atlantis Complex",
    author: "Eoin Colfer",
    rating: "9.6/10",
    genre: "AF",
  },
  {
    id: 19,
    image: "https://images-na.ssl-images-amazon.com/images/I/71OIHoqedVL.jpg",
    title: "Artemis Fowl and the Last Guardian",
    author: "Eoin Colfer",
    rating: "9.8/10",
    genre: "AF",
  },
];
